#   # app:
#   #   depends_on:
#   #     - db
#   #   build: .
#   #   restart: unless-stopped
#   #   ports: 
#   #     - '3000:3000'
#   #   container_name: api-barber
#   #   networks:
#   #     - app-connect

version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /home/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
    networks:
      - app-connect
      
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - app-connect

networks: 
  app-connect:
    driver: bridge